<a href="https://colab.research.google.com/github/axshay007/Movie_recommender_system/blob/main/Movie_Recommendation_System_using_Machine_Learning_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#!cd /content/

In [ ]:
#!wget https://drive.google.com/file/d/1cCkwiVv4mgfl20ntgY3n4yApcWqqZQe6/view?usp=sharing

Data Collection and Pre-Processing

In [ ]:
#data_dir = "/content/view"

In [ ]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/movies dataset.csv',error_bad_lines=False, engine="python")

<ipython-input-25-5f59d7281585>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  movies_data = pd.read_csv('/content/movies dataset.csv',error_bad_lines=False, engine="python")
Skipping line 405: unexpected end of data


In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
# number of rows and columns in the data frame

movies_data.shape

(4803, 24)

In [ ]:
# selecting the relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast','director','genres']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'genres']


In [ ]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
# combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['genres']

In [ ]:
print(combined_features)

0      Action Adventure Fantasy Science Fiction cultu...
1      Adventure Fantasy Action ocean drug abuse exot...
2      Action Adventure Crime spy based on novel secr...
3      Action Crime Drama Thriller dc comics crime fi...
4      Action Adventure Science Fiction based on nove...
                             ...                        
398    Crime Thriller casino thief revenge heist las ...
399    Adventure Animation Family hunter mountains ga...
400    Adventure Action Science Fiction based on nove...
401    War winter sniper world war ii stalingrad Some...
402    Adventure Action Comedy Thriller hunter bounty...
Length: 403, dtype: object


In [ ]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [ ]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 478)	0.16332843197248753
  (0, 1598)	0.12015474777335367
  (0, 2644)	0.20672060339802806
  (0, 2077)	0.1768662159263527
  (0, 1787)	0.23223880963763327
  (0, 2969)	0.19179340966219038
  (0, 3392)	0.23223880963763327
  (0, 2856)	0.23223880963763327
  (0, 2706)	0.19850557587836917
  (0, 3525)	0.19850557587836917
  (0, 3477)	0.19850557587836917
  (0, 2712)	0.14567295401295885
  (0, 2341)	0.2173116159017956
  (0, 2269)	0.10296130084729727
  (0, 3473)	0.1192884727560496
  (0, 3104)	0.0693381269296274
  (0, 1004)	0.23223880963763327
  (0, 2898)	0.19179340966219038
  (0, 633)	0.2173116159017956
  (0, 3362)	0.13133481267729505
  (0, 2921)	0.28792064024287095
  (0, 1203)	0.15134800968674755
  (0, 602)	0.2173116159017956
  (0, 741)	0.23223880963763327
  (0, 1101)	0.1648752640432036
  :	:
  (402, 2586)	0.20614907701467505
  (402, 1010)	0.20614907701467505
  (402, 2770)	0.20614907701467505
  (402, 3350)	0.20614907701467505
  (402, 788)	0.19610208784089236
  (402, 2661)	0.19610208784089236
  

Cosine Similarity

In [ ]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.0992076  0.05052025 ... 0.10789183 0.06442285 0.02868099]
 [0.0992076  1.         0.04685734 ... 0.02642903 0.01257885 0.03960659]
 [0.05052025 0.04685734 1.         ... 0.06182082 0.0347235  0.02612304]
 ...
 [0.10789183 0.02642903 0.06182082 ... 1.         0.         0.0222164 ]
 [0.06442285 0.01257885 0.0347235  ... 0.         1.         0.01246725]
 [0.02868099 0.03960659 0.02612304 ... 0.0222164  0.01246725 1.        ]]


In [ ]:
print(similarity.shape)

(403, 403)


Getting the movie name from the user

In [ ]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : conjuring


In [ ]:
# creating a list with all the movie names given in the dataset


list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# getting the keywords from the user

keywords = input(' Enter movie relevant keywords : ')

 Enter movie relevant keywords : evil


In [ ]:
# creating a list with all the keywords given in the dataset

list_of_all_keywords = movies_data['keywords'].tolist()
print(list_of_all_keywords)

['culture clash future space war space colony society', "ocean drug abuse exotic island east india trading company love of one's life", 'spy based on novel secret agent sequel mi6', 'dc comics crime fighter terrorist secret identity burglar', 'based on novel mars medallion space travel princess', "dual identity amnesia sandstorm love of one's life forgiveness", 'hostage magic horse fairy tale musical', 'marvel comic sequel superhero based on comic book vision', 'witch magic broom school of witchcraft wizardry', 'dc comics vigilante superhero based on comic book revenge', 'saving the world dc comics invulnerability sequel superhero', 'killing undercover secret agent british secret service', 'witch fortune teller bondage exotic island monster', 'texas horse survivor texas ranger partner', 'saving the world dc comics superhero based on comic book superhuman', 'based on novel fictional place brother sister relationship lion human being', 'new york shield marvel comic superhero based on com

In [ ]:
# getting the genre of the movie from the user

genre = input(' Enter movie''s genre : ')

 Enter movies genre : horror


In [ ]:
# creating a list with all the genres given in the dataset

list_of_all_genres = movies_data['genres'].tolist()
print(list_of_all_genres)

['Action Adventure Fantasy Science Fiction', 'Adventure Fantasy Action', 'Action Adventure Crime', 'Action Crime Drama Thriller', 'Action Adventure Science Fiction', 'Fantasy Action Adventure', 'Animation Family', 'Action Adventure Science Fiction', 'Adventure Fantasy Family', 'Action Adventure Fantasy', 'Adventure Fantasy Action Science Fiction', 'Adventure Action Thriller Crime', 'Adventure Fantasy Action', 'Action Adventure Western', 'Action Adventure Fantasy Science Fiction', 'Adventure Family Fantasy', 'Science Fiction Action Adventure', 'Adventure Action Fantasy', 'Action Comedy Science Fiction', 'Action Adventure Fantasy', 'Action Adventure Fantasy', 'Action Adventure', 'Adventure Fantasy', 'Adventure Fantasy', 'Adventure Drama Action', 'Drama Romance Thriller', 'Adventure Action Science Fiction', 'Thriller Action Adventure Science Fiction', 'Action Adventure Science Fiction Thriller', 'Action Adventure Thriller', 'Action Adventure Fantasy', 'Action Adventure Science Fiction', '

# Adding more attributes

In [ ]:
"""import difflib

def find_close_match(movie_name, genre=None, keywords=None):
    movie_titles = [movie['title'] for movie in movie_data]
    if genre:
        movie_titles = [movie['title'] for movie in movie_data if movie['genre'] == genre]
    if keywords:
        movie_titles = [movie['title'] for movie in movie_data if set(keywords).issubset(set(movie['keywords']))]
    close_matches = difflib.get_close_matches(movie_name, movie_titles)
    return close_matches


movie_name = 'The Shawshank Redemption'
genre = 'Drama'
keywords = ['prison', 'friendship']
close_matches = find_close_match(movie_name, genre=genre, keywords=keywords)
print(close_matches)"""

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

In [ ]:
close_match = find_close_match[0]
print(close_match)

In [ ]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

In [ ]:
len(similarity_score)

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

In [ ]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<5):
    print(i, '.',title_from_index)
    i+=1

Movie Recommendation Sytem

In [ ]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<5):
    print(i, '.',title_from_index)
    i+=1